# Generated by Django 6.1.1 on 2026-09-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_remove_product_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreceipt',
            name='warehouse',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='products.product', verbose_name='Sản phẩm'),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
