# Generated by Django 6.1.1 on 2026-09-15 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Mã đơn hàng')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Tên khách hàng')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('shipping_address', models.TextField(verbose_name='Địa chỉ nhận hàng')),
                ('priority', models.IntegerField(choices=[(1, '1 - Tiêu chuẩn (Normal)'), (2, '2 - Giao nhanh (High)'), (3, '3 - Hỏa tốc / Đơn gấp (Urgent)')], db_index=True, default=1, verbose_name='Mức độ ưu tiên')),
                ('is_urgent', models.BooleanField(db_index=True, default=False, verbose_name='Đơn hỏa tốc / Đơn gấp')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Hạn chót xử lý / Giao hàng')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('CONFIRMED', 'Đã xác nhận'), ('PROCESSING', 'Đang đóng gói / Xử lý kho'), ('SHIPPED', 'Đang vận chuyển'), ('DELIVERED', 'Đã giao hàng'), ('CANCELLED', 'Đã hủy')], db_index=True, default='PENDING', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng tiền')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú đơn hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên xử lý')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Quản lý đơn hàng',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Đơn giá')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Thành tiền')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong đơn',
                'verbose_name_plural': 'Chi tiết sản phẩm đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='OrderProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Hành động')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú thêm')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.order', verbose_name='Đơn hàng')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Nhật ký xử lý đơn',
                'verbose_name_plural': 'Nhật ký xử lý đơn',
                'ordering': ['-timestamp'],
            },
        ),
    ]
