# Generated by Django 6.1.1 on 2026-09-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang kinh doanh'),
        ),
    ]
